dist: bionic
language: python
before_install:
  - sudo apt-get -y install build-essential 
  - sudo apt-get -y install clang-9
  - sudo apt-get -y install ninja-build
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libboost-all-dev
  - sudo apt-get -y install ragel
  - sudo apt-get -y install libpcre3-dev
  - sudo apt-get -y install samtools
  - sudo apt-get -y install bwa
python:
  - "3.8.2"
  - "3.9-dev"
install:
  - pip -vvv install pytest
  - pip -vvv install numpy
  - pip -vvv install .
script:
  - pytest
