dist: bionic
language: python
before_install:
- sudo apt-get update
python:
- '3.8'
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment -c conda-forge -c bioconda -y python=$TRAVIS_PYTHON_VERSION
  clang gxx_linux-64 pip numpy=1.18 samtools=1.10 bwa ninja cmake boost pcre pkgconfig
  pytest ragel
- conda activate test-environment
- pip install .
script:
- pytest
before_deploy:
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  edge: true
  provider: releases
  token: $GITHUB_TOKEN
  prerelease: true
  draft: true
dd:
  secure: gDneCwdgqFHZEQ/dbF89g2a5S0b71MvVXcKjAg+rG4CdRszSEVVDsDHwvyiQzsas/5QAv5wcYegDJwSco8q8u3pdMWxGwPPRposyVo/lbT8cPRMK1ANMhtpfTEiZiJIAUxqBQLbrSLqwV40S0A3K/gPWYF2boHaWweLCqRZW74sJoE3HVWnR6cmgw7PJJqgHA7jjtouD9IK6nRTKdUFTMU+VzW2fVFy3nb9WcB41kN2MFGoB22zbbyCMKtVM7dXWISi1Xitpyw33PazmDhNyfQgnpGAylCHhny2uQOSy1FAcQXhgZU4w7ibWbLulzoIcZr/NEr9Y6GdRmdBBbghJS1XiX+Q7O12v5kIzOwkmtzncBHDtjxv4MFeKhM2mBixs3QIN/xunP2pkY6+LX/FhruPesfJn1RApnQe7ZKLqBR0WLFZsZS7pu4M+EZE1VALClm8fJ3EIyjD/P43Ajmxilv/3E9Hkv2MY/xss7+DN3/gKAQ0eetA9hqFxi/EX9yoB3KzO0pyDHlM7c7iMYMPZYOxxZUzoUSCjMCEM4FSEVDdesmXI+dVPCZ7u575dfHljGo7PVmKY7jpRSKtqIUpLc9Ml4AVaSqsW1FgzDmQI78MWvhg0uTKdoRTX6PmMXLzLfN53ZQL3z0F/p7mSQFgr7R/eP/nmxPQeFu2LNX9n+HE=
  on:
    branch: devel
