dist: bionic
language: python
before_install:
  - sudo apt-get update
python:
  - "3.8"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge -c bioconda -y python=$TRAVIS_PYTHON_VERSION clang gxx_linux-64 pip numpy=1.18 samtools=1.10 bwa ninja cmake boost pcre pkgconfig pytest ragel
  - conda activate test-environment
  - pip install .
script:
  - pytest
