jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

language: c
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export conda_url=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export conda_url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; fi
- wget $conda_url -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then export toolchain=clangxx_osx-64; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export toolchain=gxx_linux-64; fi
- conda create -q -n test-environment -c conda-forge -c bioconda -y python=3.8 clang=9 $toolchain pip numpy=1.18 samtools=1.10 bwa ninja cmake boost pcre pkgconfig pytest ragel
- conda activate test-environment
- pip install .
script:
- pytest
before_deploy:
- echo "Auto release generated by Travis CI on "$(date +'%Y:%m:%d at %H:%M:%S') > release_notes
- export release_name="HiLine-"$(git describe --tags)
deploy:
  edge: true
  provider: releases
  token: "$GITHUB_TOKEN"
  file: release_notes
  name: "$release_name"
  body: "Auto-generated release by Travis CI"
  prerelease: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
env:
  secure: dGBrOPz0Wr690rQ5SQEnSBpgsuMN67BEnkp9In8Cqry6wpZNzMkvopO+b6Glxpjrd2VLisALFmgazpB2zLsLuL9pi4sgVQlrxjIIGftM3Z0SXIAW6Q/3AEPdU2gCpa1io5wpiPAoGbe2HO7XGmhYmPnN5j2Y/CBFJTOPx/a4S3JhQqxhKugL5DVm87AFKOTgOplapVsYmtydHTZo9sPQCAEQHwchKo3q13+6LkLc2fowA386Q8Q+Xp8QtN5jlqqmPcCt8g/E36+9k2810YzqqjwpGhVdTnW46N8UBLugHtxBYtH3/H1cmDqnIj+JsImxJWwMi04nBnekxlgdVaiKQxCVazh2hQr1NHmK+0YQlLaM7Jigmtzh/NFdAJLKomkzL2Pica7ID5E+0y4IkNGWqj5D5K+RIRS9fvf+x9aBzKpc2y9ybgx1dEhc0SCBt9mErjlfjJNesnblo2gCCZ61fy0nIsuXTFr6nJaO3IF35+ifIE1Jy9IHKhifNdaytC3Y7K6IIJvJaUBKrMsDUw8Du4XbkcyMc/SwXbO63HewElEK0eRA4aTt+oVhvpCS9zbpLhDLqV582hDzyNa9c7IuqhwyEXwKu18SYz0GfHMQLBgFXa4/+LWt9BQwGPHc4ce1YZZC57LlUeOIsQ2JNZgxxtOG58Ho0bwqVneerpl4Mcs=
